image: docker:stable

stages:
  - Build image
  - Push to Docker Hub

variables:
  LATEST_VER: $CI_REGISTRY/soplanning:alpine
  MAJOR_VER:  $CI_REGISTRY/soplanning:1.4-alpine
  MINOR_VER:  $CI_REGISTRY/soplanning:1.43-alpine
  PATCH_VER:  $CI_REGISTRY/soplanning:1.43.0-alpine

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

docker build:
  stage: Build image
  script:
    - docker build -t $LATEST_VER -t $MAJOR_VER -t $MINOR_VER -t $PATCH_VER 1.43/alpine/
  only:
    changes:
      - 1.43/alpine/**

docker push:
  stage: Push to Docker Hub
  only:
    - master
  script:
    - docker push $LATEST_VER
    - docker push $MAJOR_VER
    - docker push $MINOR_VER
    - docker push $PATCH_VER
