image: docker:stable

stages:
  - Build Alpine image
  - Build Stretch image
  - Push to Registry

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

docker build:
  stage: Build Alpine image
  variables:
    LATEST_VER: $CI_REGISTRY_IMAGE:alpine
    MAJOR_VER:  $CI_REGISTRY_IMAGE:1.43-alpine
  script:
   - docker build --pull -t $LATEST_VER -t $MAJOR_VER 1.43/alpine/
  only:
    - master

docker build:
  stage: Build Stretch image
  variables:
    LATEST_VER: $CI_REGISTRY_IMAGE:latest
    MAJOR_VER:  $CI_REGISTRY_IMAGE:1.43
  script:
   - docker build --pull -t $LATEST_VER -t $MAJOR_VER -t ${MAJOR_VER}-stretch 1.43/stretch/
  only:
    - master

docker push:
  stage: Push to Registry
  variables:
    LATEST_VER:        $CI_REGISTRY_IMAGE:latest
    MAJOR_VER:         $CI_REGISTRY_IMAGE:1.43
    VARIANT_VER:       $CI_REGISTRY_IMAGE:alpine
    VARIANT_MAJOR_VER: $CI_REGISTRY_IMAGE:1.43-alpine
  script:
    - docker push $LATEST_VER
    - docker push $MAJOR_VER
    - docker push $VARIANT_VER
    - docker push $VARIANT_MAJOR_VER
  only:
    - master
